apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-kapt'

// Load keystore
def keystorePropertiesFile = rootProject.file("keystore.properties")
def keystoreProperties = new Properties()
keystoreProperties.load(new FileInputStream(keystorePropertiesFile))

android {
    compileSdkVersion 30
    applicationVariants.all { variant ->
        variant.outputs.all {
            outputFileName = "CometOTP-${variant.name}-${variant.versionName}.apk"
        }
    }

    defaultConfig {
        applicationId "com.gigabytedevelopersinc.app.CometOTP"
        minSdkVersion 22
        targetSdkVersion 30
        versionCode 29
        versionName "5.3.2"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables.useSupportLibrary = true
        multiDexEnabled true
    }

    signingConfigs {
        release
        release {
            storeFile file(keystoreProperties['storeFile'])
            storePassword keystoreProperties['storePassword']
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        debug {
            applicationIdSuffix = ".dev"
            versionNameSuffix = "-dev"
            testCoverageEnabled = true

            tasks.withType(JavaCompile) {
                options.compilerArgs << "-Xlint:unchecked" << "-Xlint:deprecation"
            }
        }
    }

    lintOptions {
        checkReleaseBuilds false
        abortOnError false
        disable 'MissingTranslation'
        disable 'ExtraTranslation'
    }

    dataBinding {
        enabled = true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    def lifecycle_version = "2.2.0"
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation "commons-codec:commons-codec:1.12"
    implementation "androidx.appcompat:appcompat:1.2.0"
    implementation "androidx.browser:browser:1.2.0"
    implementation "androidx.cardview:cardview:1.0.0"
    implementation "androidx.core:core-ktx:1.3.2"
    implementation "androidx.recyclerview:recyclerview:1.2.0-alpha06"
    implementation "androidx.constraintlayout:constraintlayout:2.0.3"
    implementation "androidx.lifecycle:lifecycle-process:$lifecycle_version"
    implementation "androidx.lifecycle:lifecycle-common-java8:$lifecycle_version"
    implementation "com.github.aakira:expandable-layout:1.6.0"
    implementation "com.google.android.material:material:1.3.0-alpha03"
    implementation "com.journeyapps:zxing-android-embedded:3.6.0"
    implementation "com.leinardi.android:speed-dial:3.1.1"
    implementation "com.vanniktech:vntnumberpickerpreference:1.0.0"
    implementation "me.zhanghai.android.materialprogressbar:library:1.4.2"
    implementation "org.sufficientlysecure:openpgp-api:12.0"
    implementation 'saschpe.android:customtabs:2.0.3'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.3.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
}

configurations {
    implementation.exclude group: "com.android.support", module: "customtabs"
}
repositories {
    mavenCentral()
}