@file:Suppress("PackageName")
package com.gigabytedevelopersinc.app.cometOTP.Utilities

import com.gigabytedevelopersinc.app.cometOTP.Database.Entry
import com.gigabytedevelopersinc.app.cometOTP.R
import com.gigabytedevelopersinc.app.cometOTP.Utilities.EntryThumbnail.EntryThumbnails
import com.gigabytedevelopersinc.app.cometOTP.Utilities.TokenCalculator.HashAlgorithm
import org.junit.Assert.assertEquals
import org.junit.Assert.assertThrows
import org.junit.Test

/**
 * The thumbnail is stored in every entry by its enum constant name ("thumbnail" in the JSON), so
 * renaming, dropping or reordering a constant silently changes what existing users see. This pins
 * the full list, in order, together with the drawable each one shows.
 */
class EntryThumbnailTest {

    @Test
    fun constantNamesOrderAndResourcesAreUnchanged() {
        val actual = EntryThumbnails.values().map { it.name to it.resource }
        assertEquals(EXPECTED.size, actual.size)
        for (i in EXPECTED.indices)
            assertEquals("constant #$i", EXPECTED[i], actual[i])
    }

    @Test
    fun valueOfIgnoreCaseMatchesStoredAndHandTypedNames() {
        assertEquals(EntryThumbnails.GitHub, EntryThumbnails.valueOfIgnoreCase("GitHub"))
        assertEquals(EntryThumbnails.Amazon, EntryThumbnails.valueOfIgnoreCase("amazon"))
        assertEquals(EntryThumbnails.AmazonWebServices, EntryThumbnails.valueOfIgnoreCase("AMAZONWEBSERVICES"))
        // Dots are dropped before the lookup, so an issuer such as "web.de" finds WebDe.
        assertEquals(EntryThumbnails.WebDe, EntryThumbnails.valueOfIgnoreCase("web.de"))
        assertEquals(EntryThumbnails.Default, EntryThumbnails.valueOfIgnoreCase("default"))
    }

    @Test
    fun valueOfIgnoreCaseRejectsUnknownAndNull() {
        assertThrows(IllegalArgumentException::class.java) { EntryThumbnails.valueOfIgnoreCase(null) }
        // On a device this is the IllegalArgumentException; on the JVM the android.util.Log call
        // just before it throws first. Either way the caller's catch falls back to Default.
        assertThrows(RuntimeException::class.java) { EntryThumbnails.valueOfIgnoreCase("NoSuchService") }
    }

    @Test
    fun valueOfFuzzyFindsAWholeWordAnywhereInTheIssuer() {
        assertEquals(EntryThumbnails.GitHub, EntryThumbnails.valueOfFuzzy("my GitHub login"))
        assertEquals(EntryThumbnails.Dropbox, EntryThumbnails.valueOfFuzzy("DROPBOX (work)"))
        assertThrows(IllegalArgumentException::class.java) { EntryThumbnails.valueOfFuzzy(null) }
        assertThrows(IllegalArgumentException::class.java) { EntryThumbnails.valueOfFuzzy("zzzz qqqq") }
    }

    /**
     * With several names in the issuer the one mentioned first wins, every time. (The patterns
     * used to live in a HashMap keyed by Pattern, which hashes by identity, so the winner changed
     * from one process to the next.)
     */
    @Test
    fun valueOfFuzzyPrefersTheNameMentionedFirst() {
        assertEquals(EntryThumbnails.Steam, EntryThumbnails.valueOfFuzzy("Steam Wallet"))
        assertEquals(EntryThumbnails.Wallet, EntryThumbnails.valueOfFuzzy("Wallet for Steam"))
        assertEquals(EntryThumbnails.Apple, EntryThumbnails.valueOfFuzzy("Apple School Manager"))
        assertEquals(EntryThumbnails.Microsoft, EntryThumbnails.valueOfFuzzy("Microsoft Office"))
        assertEquals(EntryThumbnails.Office, EntryThumbnails.valueOfFuzzy("Office by Microsoft"))
        assertEquals(EntryThumbnails.Google, EntryThumbnails.valueOfFuzzy("Google Email Privacy"))
        assertEquals(EntryThumbnails.Privacy, EntryThumbnails.valueOfFuzzy("my privacy, google and email"))
    }

    /** "Default" is not a service, so a real service in the same issuer takes precedence. */
    @Test
    fun valueOfFuzzyNeverPicksDefaultOverARealService() {
        assertEquals(EntryThumbnails.Google, EntryThumbnails.valueOfFuzzy("Default Google"))
        assertThrows(IllegalArgumentException::class.java) { EntryThumbnails.valueOfFuzzy("default account") }
    }

    /** The exact-name lookup runs before the fuzzy one, so an exact name still wins. */
    @Test
    fun anExactNameStillWinsOverFuzzyMatches() {
        fun thumbnailFor(issuer: String) = Entry(Entry.OTPType.TOTP, "JBSWY3DPEHPK3PXP", 30, 6, issuer, "l",
            HashAlgorithm.SHA1, mutableListOf()).thumbnail
        assertEquals(EntryThumbnails.MicrosoftTeams, thumbnailFor("MicrosoftTeams"))
        assertEquals(EntryThumbnails.AmazonWebServices, thumbnailFor("amazonwebservices"))
        assertEquals(EntryThumbnails.WebDe, thumbnailFor("web.de"))
        assertEquals(EntryThumbnails.Default, thumbnailFor("Default"))
        assertEquals(EntryThumbnails.Steam, thumbnailFor("Steam Wallet"))
        assertEquals(EntryThumbnails.Default, thumbnailFor("default account"))
    }

    private companion object {
        val EXPECTED = listOf(
            "Default" to R.mipmap.ic_launcher_round,
            "OneAndOne" to R.drawable.thumb_1and1,
            "OneBlu" to R.drawable.thumb_1blu,
            "OnePassword" to R.drawable.thumb_1password,
            "OneXBet" to R.drawable.thumb_1xbet,
            "TwentyThreeAndMe" to R.drawable.thumb_23andme,
            "FiveHundredPX" to R.drawable.thumb_500px,
            "Activision" to R.drawable.thumb_activision,
            "Adafruit" to R.drawable.thumb_adafruit,
            "AdGuard" to R.drawable.thumb_adguard,
            "Adobe" to R.drawable.thumb_adobe,
            "AirBNB" to R.drawable.thumb_airbnb,
            "Airbrake" to R.drawable.thumb_airbrake,
            "AirTable" to R.drawable.thumb_airtable,
            "AirVPN" to R.drawable.thumb_airvpn,
            "Algolia" to R.drawable.thumb_algolia,
            "AllegroPl" to R.drawable.thumb_allegropl,
            "Amazon" to R.drawable.thumb_amazon,
            "AmazonWebServices" to R.drawable.thumb_amazonwebservices,
            "AngelList" to R.drawable.thumb_angellist,
            "AnimeBytes" to R.drawable.thumb_animebytes,
            "Anonaddy" to R.drawable.thumb_anonaddy,
            "AnyDesk" to R.drawable.thumb_anydesk,
            "Apache" to R.drawable.thumb_apache,
            "Apple" to R.drawable.thumb_apple,
            "AppVeyor" to R.drawable.thumb_appveyor,
            "ArchLinux" to R.drawable.thumb_archlinux,
            "ArenaNet" to R.drawable.thumb_arenanet,
            "Aruba" to R.drawable.thumb_aruba,
            "Asana" to R.drawable.thumb_asana,
            "AtlanticNet" to R.drawable.thumb_atlantic_net,
            "Atlassian" to R.drawable.thumb_atlassian,
            "Autodesk" to R.drawable.thumb_autodesk,
            "AutoDNS" to R.drawable.thumb_autodns,
            "AVM" to R.drawable.thumb_avm,
            "Babiato" to R.drawable.thumb_babiato,
            "Backblaze" to R.drawable.thumb_backblaze,
            "Barter" to R.drawable.thumb_barter,
            "BattleNet" to R.drawable.thumb_battlenet,
            "BestBuy" to R.drawable.thumb_bestbuy,
            "Betterment" to R.drawable.thumb_betterment,
            "Binance" to R.drawable.thumb_binance,
            "BitBucket" to R.drawable.thumb_bitbucket,
            "Bitcoin" to R.drawable.thumb_bitcoin,
            "Bitdefender" to R.drawable.thumb_bitdefender,
            "Bitfinex" to R.drawable.thumb_bitfinex,
            "Bitget" to R.drawable.thumb_bitget,
            "Bitmex" to R.drawable.thumb_bitmex,
            "Bitpanda" to R.drawable.thumb_bitpanda,
            "BitGo" to R.drawable.thumb_bitgo,
            "BitPay" to R.drawable.thumb_bitpay,
            "Bitstamp" to R.drawable.thumb_bitstamp,
            "Bittrex" to R.drawable.thumb_bittrex,
            "Bitwala" to R.drawable.thumb_bitwala,
            "Bitwarden" to R.drawable.thumb_bitwarden,
            "Blacknight" to R.drawable.thumb_blacknight,
            "BlockchainInfo" to R.drawable.thumb_blockchain_info,
            "BlockFi" to R.drawable.thumb_blockfi,
            "Box" to R.drawable.thumb_box,
            "Boxcryptor" to R.drawable.thumb_boxcryptor,
            "Braintrust" to R.drawable.thumb_braintrust,
            "BraveRewards" to R.drawable.thumb_braverewards,
            "Bugcrowd" to R.drawable.thumb_bugcrowd,
            "Busha" to R.drawable.thumb_busha,
            "Bybit" to R.drawable.thumb_bybit,
            "Celsius" to R.drawable.thumb_celsius,
            "CEXio" to R.drawable.thumb_cexio,
            "Charles_Schwab" to R.drawable.thumb_charles_schwab,
            "ChurchTools" to R.drawable.thumb_church_tools,
            "CircleCi" to R.drawable.thumb_circleci,
            "Cisco" to R.drawable.thumb_cisco,
            "Citrix" to R.drawable.thumb_citrix,
            "ClickUp" to R.drawable.thumb_clickup,
            "CloudDownload" to R.drawable.thumb_cloud_download,
            "Cloudflare" to R.drawable.thumb_cloudflare,
            "Cloudinary" to R.drawable.thumb_cloudinary,
            "Clubhouse" to R.drawable.thumb_clubhouse,
            "Cobranded" to R.drawable.thumb_cobranded,
            "Codeberg" to R.drawable.thumb_codeberg,
            "CodeFortyTwo" to R.drawable.thumb_code42,
            "Codegiant" to R.drawable.thumb_codegiant,
            "Coinbase" to R.drawable.thumb_coinbase,
            "CoinDCX" to R.drawable.thumb_coindcx,
            "CoinJar" to R.drawable.thumb_coinjar,
            "ComputerBase" to R.drawable.thumb_computerbase,
            "ConnectWiseManage" to R.drawable.thumb_connectwise_manage,
            "Contabo" to R.drawable.thumb_contabo,
            "Cowrywise" to R.drawable.thumb_cowrywise,
            "CozyCloud" to R.drawable.thumb_cozycloud,
            "cPanel" to R.drawable.thumb_cpanel,
            "Crowdin" to R.drawable.thumb_crowdin,
            "CrowdSupply" to R.drawable.thumb_crowd_supply,
            "CryptoCom" to R.drawable.thumb_crypto_com,
            "CryptoComDeFiWallet" to R.drawable.thumb_crypto_com_defi_wallet,
            "CTemplar" to R.drawable.thumb_ctemplar,
            "Cyon" to R.drawable.thumb_cyon,
            "Dashlane" to R.drawable.thumb_dashlane,
            "Debian" to R.drawable.thumb_debian,
            "Degiro" to R.drawable.thumb_degiro,
            "Denic" to R.drawable.thumb_denic,
            "Deribit" to R.drawable.thumb_deribit,
            "Diaspora" to R.drawable.thumb_diaspora,
            "Digidentity" to R.drawable.thumb_digidentity,
            "DigitalOcean" to R.drawable.thumb_digital_ocean,
            "Digitec" to R.drawable.thumb_digitec,
            "Directus" to R.drawable.thumb_directus,
            "Discogs" to R.drawable.thumb_discogs,
            "Discord" to R.drawable.thumb_discord,
            "Discourse" to R.drawable.thumb_discourse,
            "Disroot" to R.drawable.thumb_disroot,
            "Docker" to R.drawable.thumb_docker,
            "DocuSign" to R.drawable.thumb_docusign,
            "DreamHost" to R.drawable.thumb_dreamhost,
            "Dropbox" to R.drawable.thumb_dropbox,
            "Drupal" to R.drawable.thumb_drupal,
            "Ecloud" to R.drawable.thumb_ecloud,
            "ElectronicArts" to R.drawable.thumb_electronic_arts,
            "Email" to R.drawable.thumb_email,
            "Eneba" to R.drawable.thumb_eneba,
            "Envato" to R.drawable.thumb_envato,
            "EpicGames" to R.drawable.thumb_epic_games,
            "ESEA" to R.drawable.thumb_esea,
            "Etsy" to R.drawable.thumb_etsy,
            "Eveonline" to R.drawable.thumb_eveonline,
            "Evernote" to R.drawable.thumb_evernote,
            "Facebook" to R.drawable.thumb_facebook,
            "FACEIT" to R.drawable.thumb_faceit,
            "Fanatical" to R.drawable.thumb_fanatical,
            "Fastmail" to R.drawable.thumb_fastmail,
            "FidelityInvestments" to R.drawable.thumb_fidelity_investments,
            "Figma" to R.drawable.thumb_figma,
            "Fingerprint" to R.drawable.thumb_fingerprint,
            "Finnair" to R.drawable.thumb_finnair,
            "Fireblocks" to R.drawable.thumb_fireblocks,
            "Firefox" to R.drawable.thumb_firefox,
            "Flight" to R.drawable.thumb_flight_takeoff,
            "Floatplane" to R.drawable.thumb_floatplane,
            "FluidFinance" to R.drawable.thumb_fluid_finance,
            "Friendica" to R.drawable.thumb_friendica,
            "Fritz" to R.drawable.thumb_fritz,
            "FTX" to R.drawable.thumb_ftx,
            "Galaxus" to R.drawable.thumb_galaxus,
            "Gamepad" to R.drawable.thumb_gamepad,
            "Gandi" to R.drawable.thumb_gandi,
            "GateIo" to R.drawable.thumb_gate_io,
            "Geegpay" to R.drawable.thumb_geegpay,
            "Gemini" to R.drawable.thumb_gemini,
            "GigabyteDevelopers" to R.drawable.thumb_gigabyte_developers,
            "Git" to R.drawable.thumb_git,
            "Gitea" to R.drawable.thumb_gitea,
            "GitHub" to R.drawable.thumb_github,
            "GitLab" to R.drawable.thumb_gitlab,
            "GMX" to R.drawable.thumb_gmx,
            "Go54" to R.drawable.thumb_go54,
            "GoatCounter" to R.drawable.thumb_goatcounter,
            "GoDaddy" to R.drawable.thumb_godaddy,
            "Gogs" to R.drawable.thumb_gogs,
            "Google" to R.drawable.thumb_google,
            "GovUK" to R.drawable.thumb_gov_uk,
            "Grammarly" to R.drawable.thumb_grammarly,
            "Greenhost" to R.drawable.thumb_greenhost,
            "Grey" to R.drawable.thumb_grey,
            "GTwoA" to R.drawable.thumb_g2a,
            "HackerOne" to R.drawable.thumb_hackerone,
            "Heroku" to R.drawable.thumb_heroku,
            "Hetzner" to R.drawable.thumb_hetzner,
            "HitBTC" to R.drawable.thumb_hitbtc,
            "HMRC" to R.drawable.thumb_gov_uk,
            "HomeAssistant" to R.drawable.thumb_home_assistant,
            "HostingDE" to R.drawable.thumb_hosting_de,
            "Hover" to R.drawable.thumb_hover,
            "Huawei" to R.drawable.thumb_huawei,
            "HubSpot" to R.drawable.thumb_hubspot,
            "HumbleBundle" to R.drawable.thumb_humblebundle,
            "HurricaneElectric" to R.drawable.thumb_hurricane_electric,
            "IBM" to R.drawable.thumb_ibm,
            "Iconomi" to R.drawable.thumb_iconomi,
            "IFTTT" to R.drawable.thumb_ifttt,
            "ImmoScout24" to R.drawable.thumb_immo_scout24,
            "Improvmx" to R.drawable.thumb_improvmx,
            "Infomaniak" to R.drawable.thumb_infomaniak,
            "Instagram" to R.drawable.thumb_instagram,
            "Intercom" to R.drawable.thumb_intercom,
            "INWX" to R.drawable.thumb_inwx,
            "Itchio" to R.drawable.thumb_itchio,
            "Jagex" to R.drawable.thumb_jagex,
            "JetBrains" to R.drawable.thumb_jetbrains,
            "Joomla" to R.drawable.thumb_joomla,
            "KDE" to R.drawable.thumb_kde,
            "Keeper" to R.drawable.thumb_keeper,
            "Keycloak" to R.drawable.thumb_keycloak,
            "Keyhelp" to R.drawable.thumb_keyhelp,
            "Kickstarter" to R.drawable.thumb_kickstarter,
            "Kraken" to R.drawable.thumb_kraken,
            "Kucoin" to R.drawable.thumb_kucoin,
            "LastPass" to R.drawable.thumb_lastpass,
            "LibreNMS" to R.drawable.thumb_librenms,
            "Lichess" to R.drawable.thumb_lichess,
            "LinkedIn" to R.drawable.thumb_linkedin,
            "Linode" to R.drawable.thumb_linode,
            "LinusTechTips" to R.drawable.thumb_linustechtips,
            "Liqui" to R.drawable.thumb_liqui,
            "LivelyMe" to R.drawable.thumb_livelyme,
            "Lobsters" to R.drawable.thumb_lobsters,
            "LocalBitcoins" to R.drawable.thumb_localbitcoins,
            "LocalMonero" to R.drawable.thumb_localmonero,
            "LoginGov" to R.drawable.thumb_login_gov,
            "LogMeIn" to R.drawable.thumb_logmein,
            "LuaDNS" to R.drawable.thumb_luadns,
            "Luno" to R.drawable.thumb_luno,
            "Mailbox" to R.drawable.thumb_mailbox,
            "Mailchimp" to R.drawable.thumb_mailchimp,
            "Mailcow" to R.drawable.thumb_mailcow,
            "MailDE" to R.drawable.thumb_mail_de,
            "Mailgun" to R.drawable.thumb_mailgun,
            "Mailru" to R.drawable.thumb_mailru,
            "Malwaretips" to R.drawable.thumb_malwaretips,
            "Mangadex" to R.drawable.thumb_mangadex,
            "Manitu" to R.drawable.thumb_manitu,
            "Mapbox" to R.drawable.thumb_mapbox,
            "Mastodon" to R.drawable.thumb_mastodon,
            "Matomo" to R.drawable.thumb_matomo,
            "Mattermost" to R.drawable.thumb_mattermost,
            "Mediawiki" to R.drawable.thumb_mediawiki,
            "Mega" to R.drawable.thumb_mega,
            "MercadoLibre" to R.drawable.thumb_mercadolibre,
            "Mercury" to R.drawable.thumb_mercury,
            "Microsoft" to R.drawable.thumb_microsoft,
            "MicrosoftTeams" to R.drawable.thumb_microsoft_teams,
            "Migadu" to R.drawable.thumb_migadu,
            "Migros" to R.drawable.thumb_migros,
            "Mint" to R.drawable.thumb_mint,
            "Miraheze" to R.drawable.thumb_miraheze,
            "Mixer" to R.drawable.thumb_mixer,
            "MOneFinance" to R.drawable.thumb_m1finance,
            "MongoDB" to R.drawable.thumb_mongodb,
            "MVPSnet" to R.drawable.thumb_mvpsnet,
            "MyGovAU" to R.drawable.thumb_my_gov_au,
            "NameCheap" to R.drawable.thumb_namecheap,
            "NameCom" to R.drawable.thumb_namecom,
            "NameSilo" to R.drawable.thumb_namesilo,
            "NAS" to R.drawable.thumb_nas,
            "Netcup" to R.drawable.thumb_netcup,
            "Netlify" to R.drawable.thumb_netlify,
            "NewEgg" to R.drawable.thumb_newegg,
            "Nexo" to R.drawable.thumb_nexo,
            "NextCloud" to R.drawable.thumb_nextcloud,
            "NextDNS" to R.drawable.thumb_nextdns,
            "NexusMods" to R.drawable.thumb_nexusmods,
            "NiceHash" to R.drawable.thumb_nicehash,
            "Nintendo" to R.drawable.thumb_nintendo,
            "Nord" to R.drawable.thumb_nord,
            "NoStarchPress" to R.drawable.thumb_no_starch_press,
            "NPM" to R.drawable.thumb_npm,
            "NTPPoolProject" to R.drawable.thumb_ntppoolproject,
            "NVIDIA" to R.drawable.thumb_nvidia,
            "Oculus" to R.drawable.thumb_oculus,
            "Office" to R.drawable.thumb_office,
            "Okex" to R.drawable.thumb_okex,
            "Okta" to R.drawable.thumb_okta,
            "OnlineNet" to R.drawable.thumb_online,
            "Onlyfans" to R.drawable.thumb_onlyfans,
            "Onshape" to R.drawable.thumb_onshape,
            "OpenAI" to R.drawable.thumb_openai,
            "OpenVPN" to R.drawable.thumb_openvpn,
            "OpenVZ" to R.drawable.thumb_openvz,
            "Opera" to R.drawable.thumb_opera,
            "OPNsense" to R.drawable.thumb_opnsense,
            "ORCiD" to R.drawable.thumb_orcid,
            "OtterAI" to R.drawable.thumb_otter_ai,
            "Origin" to R.drawable.thumb_origin,
            "OVH" to R.drawable.thumb_ovh,
            "Packet" to R.drawable.thumb_packet,
            "Papaki" to R.drawable.thumb_papaki,
            "Parsecgaming" to R.drawable.thumb_parsecgaming,
            "Passwordstate" to R.drawable.thumb_passwordstate,
            "Patreon" to R.drawable.thumb_patreon,
            "PayPal" to R.drawable.thumb_paypal,
            "PaySafe" to R.drawable.thumb_paysafecard,
            "Paystack" to R.drawable.thumb_paystack,
            "Payza" to R.drawable.thumb_payza,
            "PCloud" to R.drawable.thumb_pcloud,
            "PeeringDB" to R.drawable.thumb_peeringdb,
            "Percona" to R.drawable.thumb_percona,
            "Phabricator" to R.drawable.thumb_phabricator,
            "phpMyAdmin" to R.drawable.thumb_phpmyadmin,
            "Pixelfed" to R.drawable.thumb_pixelfed,
            "PlayStation" to R.drawable.thumb_playstation,
            "Pleroma" to R.drawable.thumb_pleroma,
            "Plesk" to R.drawable.thumb_plesk,
            "Plex" to R.drawable.thumb_plex,
            "Pluralsight" to R.drawable.thumb_pluralsight,
            "Plurk" to R.drawable.thumb_plurk,
            "POEditor" to R.drawable.thumb_poeditor,
            "Porkbun" to R.drawable.thumb_porkbun,
            "Posteo" to R.drawable.thumb_posteo,
            "Pretix" to R.drawable.thumb_pretix,
            "Prey" to R.drawable.thumb_prey,
            "Privacy" to R.drawable.thumb_privacy,
            "PrivateInternetAccess" to R.drawable.thumb_private_internet_access,
            "ProtonMail" to R.drawable.thumb_protonmail,
            "ProtonVPN" to R.drawable.thumb_protonvpn,
            "Proxmox" to R.drawable.thumb_proxmox,
            "PulseHeberg" to R.drawable.thumb_pulseheberg,
            "Purse" to R.drawable.thumb_purse,
            "Pushover" to R.drawable.thumb_pushover,
            "PyPI" to R.drawable.thumb_pypi,
            "PythonAnywhere" to R.drawable.thumb_python_anywhere,
            "Rackspace" to R.drawable.thumb_rackspace,
            "Razer" to R.drawable.thumb_razer,
            "Reddit" to R.drawable.thumb_reddit,
            "RedHat" to R.drawable.thumb_redhat,
            "Reloadly" to R.drawable.thumb_reloadly,
            "RipeNNC" to R.drawable.thumb_ripe_ncc,
            "Ripio" to R.drawable.thumb_ripio,
            "Robinhood" to R.drawable.thumb_robinhood,
            "RocketChat" to R.drawable.thumb_rocket_chat,
            "Rockstar" to R.drawable.thumb_rockstar,
            "Roundcube" to R.drawable.thumb_roundcube,
            "RSS" to R.drawable.thumb_rss,
            "RubyGems" to R.drawable.thumb_rubygems,
            "Samsung" to R.drawable.thumb_samsung,
            "SAP" to R.drawable.thumb_sap,
            "Saxobank" to R.drawable.thumb_saxobank,
            "Scaleway" to R.drawable.thumb_scaleway,
            "Sciebo" to R.drawable.thumb_sciebo,
            "Seafile" to R.drawable.thumb_seafile,
            "SelfWealth" to R.drawable.thumb_selfwealth,
            "School" to R.drawable.thumb_school,
            "Sentry" to R.drawable.thumb_sentry,
            "ServiceNow" to R.drawable.thumb_servicenow,
            "Sevdesk" to R.drawable.thumb_sevdesk,
            "SimpleLogin" to R.drawable.thumb_simple_login,
            "ShopperCom" to R.drawable.thumb_shopper_com,
            "Skrill" to R.drawable.thumb_skrill,
            "Slack" to R.drawable.thumb_slack,
            "Smartbill" to R.drawable.thumb_smartbill,
            "Smartschool" to R.drawable.thumb_smartschool,
            "Snapchat" to R.drawable.thumb_snapchat,
            "SOGo" to R.drawable.thumb_sogo,
            "Sophos" to R.drawable.thumb_sophos,
            "SourceForge" to R.drawable.thumb_sourceforge,
            "Sourcehut" to R.drawable.thumb_sourcehut,
            "SquareEnix" to R.drawable.thumb_squareenix,
            "Squarespace" to R.drawable.thumb_squarespace,
            "Stack" to R.drawable.thumb_stack,
            "Stake" to R.drawable.thumb_stake,
            "StandardNotes" to R.drawable.thumb_standardnotes,
            "StarCitizen" to R.drawable.thumb_starcitizen,
            "Steam" to R.drawable.thumb_steam,
            "STEPN" to R.drawable.thumb_stepn,
            "Strato" to R.drawable.thumb_strato,
            "Stripe" to R.drawable.thumb_stripe,
            "Sumologic" to R.drawable.thumb_sumologic,
            "Sync" to R.drawable.thumb_sync,
            "Synology" to R.drawable.thumb_synology,
            "TeaHub" to R.drawable.thumb_teahub,
            "TeamViewer" to R.drawable.thumb_teamviewer,
            "Terminal" to R.drawable.thumb_terminal,
            "TerraformCloud" to R.drawable.thumb_terraform_cloud,
            "TeslaMotors" to R.drawable.thumb_tesla_motors,
            "Tildes" to R.drawable.thumb_tildes,
            "TMobile" to R.drawable.thumb_t_mobile,
            "TradingView" to R.drawable.thumb_tradingview,
            "TransIP" to R.drawable.thumb_transip,
            "Trello" to R.drawable.thumb_trello,
            "Tresorit" to R.drawable.thumb_tresorit,
            "TruckersMP" to R.drawable.thumb_truckersmp,
            "TruthSocial" to R.drawable.thumb_truthsocial,
            "Tumblr" to R.drawable.thumb_tumblr,
            "TUBerlin" to R.drawable.thumb_tu_berlin,
            "TurboTax" to R.drawable.thumb_turbotax,
            "Tutanota" to R.drawable.thumb_tutanota,
            "TUWien" to R.drawable.thumb_tuwien_ac_at,
            "Tweakers" to R.drawable.thumb_tweakers,
            "Twilio" to R.drawable.thumb_twilio,
            "Twitch" to R.drawable.thumb_twitch,
            "Twitter" to R.drawable.thumb_twitter,
            "Uber" to R.drawable.thumb_uber,
            "UbiquitiNetworks" to R.drawable.thumb_ubiquiti,
            "Ubisoft" to R.drawable.thumb_ubisoft,
            "UbuntuOne" to R.drawable.thumb_ubuntu_one,
            "Ultimaker" to R.drawable.thumb_ultimaker,
            "Unity" to R.drawable.thumb_unity,
            "Uphold" to R.drawable.thumb_uphold,
            "UptimeRobot" to R.drawable.thumb_uptime_robot,
            "Upwork" to R.drawable.thumb_upwork,
            "USAA" to R.drawable.thumb_usaa,
            "VagrantCloud" to R.drawable.thumb_vagrant_cloud,
            "VexxHost" to R.drawable.thumb_vexxhost,
            "VK" to R.drawable.thumb_vk,
            "VMware" to R.drawable.thumb_vmware,
            "Vultr" to R.drawable.thumb_vultr,
            "Wallabag" to R.drawable.thumb_wallabag,
            "Wallet" to R.drawable.thumb_wallet,
            "WalletsOne" to R.drawable.thumb_wallets_one,
            "Wargaming" to R.drawable.thumb_wargaming,
            "Wasabi" to R.drawable.thumb_wasabi,
            "Wazir" to R.drawable.thumb_wazir,
            "WebDe" to R.drawable.thumb_web_de,
            "Weclapp" to R.drawable.thumb_weclapp,
            "Whogohost" to R.drawable.thumb_whogohost,
            "Werknemerloket" to R.drawable.thumb_werknemerloket,
            "Wikimedia" to R.drawable.thumb_wikimedia,
            "Wildduck" to R.drawable.thumb_wildduck,
            "Windscribe" to R.drawable.thumb_windscribe,
            "WooCommerce" to R.drawable.thumb_woocommerce,
            "Wordpress" to R.drawable.thumb_wordpress,
            "Workplace" to R.drawable.thumb_workplace,
            "XDADevelopers" to R.drawable.thumb_xda_developers,
            "XendFinance" to R.drawable.thumb_xend_finance,
            "Xero" to R.drawable.thumb_xero,
            "Xerox" to R.drawable.thumb_xerox,
            "Xing" to R.drawable.thumb_xing,
            "Yahoo" to R.drawable.thumb_yahoo,
            "YandexMoney" to R.drawable.thumb_yandex_money,
            "YoYoGames" to R.drawable.thumb_yoyogames,
            "Zapier" to R.drawable.thumb_zapier,
            "Zendesk" to R.drawable.thumb_zendesk,
            "Zoho" to R.drawable.thumb_zoho,
            "Zoom" to R.drawable.thumb_zoom
        )
    }
}
